// <auto-generated />
using System;
using HbcRest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HbcRest.Migrations
{
    [DbContext(typeof(HbcContext))]
    [Migration("20251225222625_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("HbcRest.Data.CallCenterInquiry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Agency")
                        .HasColumnType("TEXT")
                        .HasColumnName("agency")
                        .HasAnnotation("Relational:JsonPropertyName", "agency");

                    b.Property<string>("AgencyName")
                        .HasColumnType("TEXT")
                        .HasColumnName("agency_name")
                        .HasAnnotation("Relational:JsonPropertyName", "agency_name");

                    b.Property<string>("BriefDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("brief_description")
                        .HasAnnotation("Relational:JsonPropertyName", "brief_description");

                    b.Property<string>("CallResolution")
                        .HasColumnType("TEXT")
                        .HasColumnName("call_resolution")
                        .HasAnnotation("Relational:JsonPropertyName", "call_resolution");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_time")
                        .HasAnnotation("Relational:JsonPropertyName", "date_time");

                    b.Property<string>("HbcUniqueKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("hbc_unique_key")
                        .HasAnnotation("Relational:JsonPropertyName", "hbc_unique_key");

                    b.Property<string>("InquiryName")
                        .HasColumnType("TEXT")
                        .HasColumnName("inquiry_name")
                        .HasAnnotation("Relational:JsonPropertyName", "inquiry_name");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time")
                        .HasAnnotation("Relational:JsonPropertyName", "time");

                    b.Property<string>("UniqueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("unique_id")
                        .HasAnnotation("Relational:JsonPropertyName", "unique_id");

                    b.HasKey("Id");

                    b.HasIndex("HbcUniqueKey")
                        .IsUnique();

                    b.ToTable("nyc_open_data_311_call_center_inquiry");
                });

            modelBuilder.Entity("HbcRest.Data.CustomerSatisfactionSurvey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AgentCustomerService")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_customer_service")
                        .HasAnnotation("Relational:JsonPropertyName", "agent_customer_service");

                    b.Property<string>("AgentJobKnowledge")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_job_knowledge")
                        .HasAnnotation("Relational:JsonPropertyName", "agent_job_knowledge");

                    b.Property<string>("AnswerSatisfaction")
                        .HasColumnType("TEXT")
                        .HasColumnName("answer_satisfaction")
                        .HasAnnotation("Relational:JsonPropertyName", "answer_satisfaction");

                    b.Property<string>("Campaign")
                        .HasColumnType("TEXT")
                        .HasColumnName("campaign")
                        .HasAnnotation("Relational:JsonPropertyName", "campaign");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT")
                        .HasColumnName("channel")
                        .HasAnnotation("Relational:JsonPropertyName", "channel");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("completion_time")
                        .HasAnnotation("Relational:JsonPropertyName", "completion_time");

                    b.Property<string>("HbcUniqueKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("hbc_unique_key")
                        .HasAnnotation("Relational:JsonPropertyName", "hbc_unique_key");

                    b.Property<int?>("Nps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nps")
                        .HasAnnotation("Relational:JsonPropertyName", "nps");

                    b.Property<string>("OverallSatisfaction")
                        .HasColumnType("TEXT")
                        .HasColumnName("overall_satisfaction")
                        .HasAnnotation("Relational:JsonPropertyName", "overall_satisfaction");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time")
                        .HasAnnotation("Relational:JsonPropertyName", "start_time");

                    b.Property<string>("SurveyLanguage")
                        .HasColumnType("TEXT")
                        .HasColumnName("survey_language")
                        .HasAnnotation("Relational:JsonPropertyName", "survey_language");

                    b.Property<string>("SurveyType")
                        .HasColumnType("TEXT")
                        .HasColumnName("survey_type")
                        .HasAnnotation("Relational:JsonPropertyName", "survey_type");

                    b.Property<string>("WaitTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("wait_time")
                        .HasAnnotation("Relational:JsonPropertyName", "wait_time");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT")
                        .HasColumnName("year")
                        .HasAnnotation("Relational:JsonPropertyName", "year");

                    b.HasKey("Id");

                    b.HasIndex("HbcUniqueKey")
                        .IsUnique();

                    b.ToTable("nyc_open_data_311_customer_satisfaction_survey");
                });

            modelBuilder.Entity("HbcRest.Data.ServiceRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AddressType")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_type")
                        .HasAnnotation("Relational:JsonPropertyName", "address_type");

                    b.Property<string>("Agency")
                        .HasColumnType("TEXT")
                        .HasColumnName("agency")
                        .HasAnnotation("Relational:JsonPropertyName", "agency");

                    b.Property<string>("AgencyName")
                        .HasColumnType("TEXT")
                        .HasColumnName("agency_name")
                        .HasAnnotation("Relational:JsonPropertyName", "agency_name");

                    b.Property<string>("Borough")
                        .HasColumnType("TEXT")
                        .HasColumnName("borough")
                        .HasAnnotation("Relational:JsonPropertyName", "borough");

                    b.Property<string>("BridgeHighwayDirection")
                        .HasColumnType("TEXT")
                        .HasColumnName("bridge_highway_direction")
                        .HasAnnotation("Relational:JsonPropertyName", "bridge_highway_direction");

                    b.Property<string>("BridgeHighwayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("bridge_highway_name")
                        .HasAnnotation("Relational:JsonPropertyName", "bridge_highway_name");

                    b.Property<string>("BridgeHighwaySegment")
                        .HasColumnType("TEXT")
                        .HasColumnName("bridge_highway_segment")
                        .HasAnnotation("Relational:JsonPropertyName", "bridge_highway_segment");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasColumnName("city")
                        .HasAnnotation("Relational:JsonPropertyName", "city");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_date")
                        .HasAnnotation("Relational:JsonPropertyName", "closed_date");

                    b.Property<string>("CommunityBoard")
                        .HasColumnType("TEXT")
                        .HasColumnName("community_board")
                        .HasAnnotation("Relational:JsonPropertyName", "community_board");

                    b.Property<string>("ComplaintType")
                        .HasColumnType("TEXT")
                        .HasColumnName("complaint_type")
                        .HasAnnotation("Relational:JsonPropertyName", "complaint_type");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date")
                        .HasAnnotation("Relational:JsonPropertyName", "created_date");

                    b.Property<string>("CrossStreet1")
                        .HasColumnType("TEXT")
                        .HasColumnName("cross_street_1")
                        .HasAnnotation("Relational:JsonPropertyName", "cross_street_1");

                    b.Property<string>("CrossStreet2")
                        .HasColumnType("TEXT")
                        .HasColumnName("cross_street_2")
                        .HasAnnotation("Relational:JsonPropertyName", "cross_street_2");

                    b.Property<string>("Descriptor")
                        .HasColumnType("TEXT")
                        .HasColumnName("descriptor")
                        .HasAnnotation("Relational:JsonPropertyName", "descriptor");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date")
                        .HasAnnotation("Relational:JsonPropertyName", "due_date");

                    b.Property<string>("FacilityType")
                        .HasColumnType("TEXT")
                        .HasColumnName("facility_type")
                        .HasAnnotation("Relational:JsonPropertyName", "facility_type");

                    b.Property<string>("FerryDirection")
                        .HasColumnType("TEXT")
                        .HasColumnName("ferry_direction")
                        .HasAnnotation("Relational:JsonPropertyName", "ferry_direction");

                    b.Property<string>("FerryTerminalName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ferry_terminal_name")
                        .HasAnnotation("Relational:JsonPropertyName", "ferry_terminal_name");

                    b.Property<string>("GarageLotName")
                        .HasColumnType("TEXT")
                        .HasColumnName("garage_lot_name")
                        .HasAnnotation("Relational:JsonPropertyName", "garage_lot_name");

                    b.Property<string>("HbcUniqueKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("hbc_unique_key")
                        .HasAnnotation("Relational:JsonPropertyName", "hbc_unique_key");

                    b.Property<string>("IncidentAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("incident_address")
                        .HasAnnotation("Relational:JsonPropertyName", "incident_address");

                    b.Property<string>("IncidentZip")
                        .HasColumnType("TEXT")
                        .HasColumnName("incident_zip")
                        .HasAnnotation("Relational:JsonPropertyName", "incident_zip");

                    b.Property<string>("IntersectionStreet1")
                        .HasColumnType("TEXT")
                        .HasColumnName("intersection_street_1")
                        .HasAnnotation("Relational:JsonPropertyName", "intersection_street_1");

                    b.Property<string>("IntersectionStreet2")
                        .HasColumnType("TEXT")
                        .HasColumnName("intersection_street_2")
                        .HasAnnotation("Relational:JsonPropertyName", "intersection_street_2");

                    b.Property<string>("Landmark")
                        .HasColumnType("TEXT")
                        .HasColumnName("landmark")
                        .HasAnnotation("Relational:JsonPropertyName", "landmark");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude")
                        .HasAnnotation("Relational:JsonPropertyName", "latitude");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasColumnName("location")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<string>("LocationType")
                        .HasColumnType("TEXT")
                        .HasColumnName("location_type")
                        .HasAnnotation("Relational:JsonPropertyName", "location_type");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude")
                        .HasAnnotation("Relational:JsonPropertyName", "longitude");

                    b.Property<string>("ParkBorough")
                        .HasColumnType("TEXT")
                        .HasColumnName("park_borough")
                        .HasAnnotation("Relational:JsonPropertyName", "park_borough");

                    b.Property<string>("ParkFacilityName")
                        .HasColumnType("TEXT")
                        .HasColumnName("park_facility_name")
                        .HasAnnotation("Relational:JsonPropertyName", "park_facility_name");

                    b.Property<DateTime?>("ResolutionActionUpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolution_action_updated_date")
                        .HasAnnotation("Relational:JsonPropertyName", "resolution_action_updated_date");

                    b.Property<string>("RoadRamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("road_ramp")
                        .HasAnnotation("Relational:JsonPropertyName", "road_ramp");

                    b.Property<string>("SchoolAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_address")
                        .HasAnnotation("Relational:JsonPropertyName", "school_address");

                    b.Property<string>("SchoolCity")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_city")
                        .HasAnnotation("Relational:JsonPropertyName", "school_city");

                    b.Property<string>("SchoolCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_code")
                        .HasAnnotation("Relational:JsonPropertyName", "school_code");

                    b.Property<string>("SchoolName")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_name")
                        .HasAnnotation("Relational:JsonPropertyName", "school_name");

                    b.Property<string>("SchoolNotFound")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_not_found")
                        .HasAnnotation("Relational:JsonPropertyName", "school_not_found");

                    b.Property<string>("SchoolNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_number")
                        .HasAnnotation("Relational:JsonPropertyName", "school_number");

                    b.Property<string>("SchoolOrCitywideComplaint")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_or_citywide_complaint")
                        .HasAnnotation("Relational:JsonPropertyName", "school_or_citywide_complaint");

                    b.Property<string>("SchoolPhoneNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_phone_number")
                        .HasAnnotation("Relational:JsonPropertyName", "school_phone_number");

                    b.Property<string>("SchoolRegion")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_region")
                        .HasAnnotation("Relational:JsonPropertyName", "school_region");

                    b.Property<string>("SchoolState")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_state")
                        .HasAnnotation("Relational:JsonPropertyName", "school_state");

                    b.Property<string>("SchoolZip")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_zip")
                        .HasAnnotation("Relational:JsonPropertyName", "school_zip");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("StreetName")
                        .HasColumnType("TEXT")
                        .HasColumnName("street_name")
                        .HasAnnotation("Relational:JsonPropertyName", "street_name");

                    b.Property<string>("TaxiCompanyBorough")
                        .HasColumnType("TEXT")
                        .HasColumnName("taxi_company_borough")
                        .HasAnnotation("Relational:JsonPropertyName", "taxi_company_borough");

                    b.Property<string>("TaxiPickUpLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("taxi_pick_up_location")
                        .HasAnnotation("Relational:JsonPropertyName", "taxi_pick_up_location");

                    b.Property<string>("UniqueKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("unique_key")
                        .HasAnnotation("Relational:JsonPropertyName", "unique_key");

                    b.Property<string>("VehicleType")
                        .HasColumnType("TEXT")
                        .HasColumnName("vehicle_type")
                        .HasAnnotation("Relational:JsonPropertyName", "vehicle_type");

                    b.Property<double?>("XCoordinateStatePlane")
                        .HasColumnType("REAL")
                        .HasColumnName("x_coordinate_state_plane_")
                        .HasAnnotation("Relational:JsonPropertyName", "x_coordinate_state_plane_");

                    b.Property<double?>("YCoordinateStatePlane")
                        .HasColumnType("REAL")
                        .HasColumnName("y_coordinate_state_plane_")
                        .HasAnnotation("Relational:JsonPropertyName", "y_coordinate_state_plane_");

                    b.HasKey("Id");

                    b.HasIndex("HbcUniqueKey")
                        .IsUnique();

                    b.ToTable("nyc_open_data_311_service_requests");
                });
#pragma warning restore 612, 618
        }
    }
}
