// <auto-generated />
using System;
using HbcRest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HbcRest.Migrations
{
    [DbContext(typeof(HbcContext))]
    partial class HbcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("HbcRest.Data.CustomerSatisfactionSurvey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("AgentCustomerService")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_customer_service")
                        .HasAnnotation("Relational:JsonPropertyName", "agent_customer_service");

                    b.Property<string>("AgentJobKnowledge")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_job_knowledge")
                        .HasAnnotation("Relational:JsonPropertyName", "agent_job_knowledge");

                    b.Property<string>("AnswerSatisfaction")
                        .HasColumnType("TEXT")
                        .HasColumnName("answer_satisfaction")
                        .HasAnnotation("Relational:JsonPropertyName", "answer_satisfaction");

                    b.Property<string>("Campaign")
                        .HasColumnType("TEXT")
                        .HasColumnName("campaign")
                        .HasAnnotation("Relational:JsonPropertyName", "campaign");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT")
                        .HasColumnName("channel")
                        .HasAnnotation("Relational:JsonPropertyName", "channel");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("completion_time")
                        .HasAnnotation("Relational:JsonPropertyName", "completion_time");

                    b.Property<int?>("Nps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nps")
                        .HasAnnotation("Relational:JsonPropertyName", "nps");

                    b.Property<string>("OverallSatisfaction")
                        .HasColumnType("TEXT")
                        .HasColumnName("overall_satisfaction")
                        .HasAnnotation("Relational:JsonPropertyName", "overall_satisfaction");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time")
                        .HasAnnotation("Relational:JsonPropertyName", "start_time");

                    b.Property<string>("SurveyLanguage")
                        .HasColumnType("TEXT")
                        .HasColumnName("survey_language")
                        .HasAnnotation("Relational:JsonPropertyName", "survey_language");

                    b.Property<string>("SurveyType")
                        .HasColumnType("TEXT")
                        .HasColumnName("survey_type")
                        .HasAnnotation("Relational:JsonPropertyName", "survey_type");

                    b.Property<string>("UniqueKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("unique_key")
                        .HasAnnotation("Relational:JsonPropertyName", "unique_key");

                    b.Property<string>("WaitTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("wait_time")
                        .HasAnnotation("Relational:JsonPropertyName", "wait_time");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT")
                        .HasColumnName("year")
                        .HasAnnotation("Relational:JsonPropertyName", "year");

                    b.HasKey("Id");

                    b.HasIndex("UniqueKey")
                        .IsUnique();

                    b.ToTable("nyc_open_data_311_customer_satisfaction_survey");
                });
#pragma warning restore 612, 618
        }
    }
}
